services:
  nginx:
    image: nginx-42
    ports:
      - 443:443
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./certificates/nginx:/etc/nginx/ssl:ro
      - static_page_data:/var/www/static_page:ro
    networks:
      - inception_network
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  mariadb:
    image: mariadb-42
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    networks:
      - inception_network
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    secrets:
      - mysql_password
      - mysql_root_password
    env_file:
      - ./env/.env_mariadb

  adminer:
    image: adminer-42
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - inception_network
    env_file:
      - ./env/.env_adminer
    healthcheck:
      test: ["CMD-SHELL", "php", "-l", "/var/www/html/index.php"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  wordpress:
    image: wordpress-42
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception_network
    secrets:
      - wordpress_db_password
    env_file:
      - ./env/.env_wordpress
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  redis:
    image: redis-42
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - redis_data:/data:rw
    networks:
      - inception_network
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  ftp-server:
    image: ftp-server-42
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception_network
    secrets:
      - ftp_password
    env_file:
      - ./env/.env_ftp_server
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 21"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  log-collector:
    image: log-collector-42
    build:
      context: ./requirements/bonus/log-collector
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - logs_data:/mnt/log_backups
    env_file:
      - ./env/.env_log_collector
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'log-collector' > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3

  static-page:
    image: static-page-42
    build:
      context: ./requirements/bonus/static_page
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - static_page_data:/var/www/html
    networks:
      - inception_network

secrets:
  mysql_password:
    external: true
  mysql_root_password:
    external: true
  wordpress_db_password:
    external: true
  redis_password:
    external: true
  ftp_password:
    external: true

volumes:
  mariadb_data:
    external: true
  wordpress_data:
    external: true
  redis_data:
    external: true
  static_page_data:
    external: true
  logs_data:
    external: true

networks:
  inception_network:
    driver: overlay
    external: true
