services:
  nginx:
    image: localhost:5000/nginx
    ports:
      - 443:443
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception_network
    secrets:
      - nginx_ssl_cert
      - nginx_ssl_key
      - nginx_ssl_dhparam
      - nginx_ssl_fullchain
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 443"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  mariadb:
    image: localhost:5000/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    networks:
      - inception_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    secrets:
      - mysql_password
      - mysql_root_password
    env_file:
      - ./env/.env_mariadb

  adminer:
    image: localhost:5000/adminer
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - inception_network
    env_file:
      - ./env/.env_adminer
    healthcheck:
      test: ["CMD-SHELL", "php", "-l", "/var/www/html/index.php"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  wordpress:
    image: localhost:5000/wordpress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception_network
    secrets:
      - wordpress_db_password
      - wordpress_admin_password
      - wordpress_user_password
      - redis_password
      - ftp_password
    env_file:
      - ./env/.env_wordpress
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  redis:
    image: localhost:5000/redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - redis_data:/data:rw
    networks:
      - inception_network
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  ftp-server:
    image: localhost:5000/ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception_network
    secrets:
      - ftp_password
      - ftp_ssl_cert
      - ftp_ssl_key
    env_file:
      - ./env/.env_ftp_server

  splunk-forwarder:
    image: localhost:5000/splunk-forwarder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - logs_data:/mnt/log_backups
    env_file:
      - ./env/.env_splunk_forwarder
    secrets:
      - splunk_forwarder_pass
      - splunk_server_ip
    tty: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  static-page:
    image: localhost:5000/static-page
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - static_page_data:/var/www/html
    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000\")' || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 15s
      retries: 3

secrets:
  mysql_password:
    external: true
  mysql_root_password:
    external: true
  wordpress_db_password:
    external: true
  wordpress_admin_password:
    external: true
  wordpress_user_password:
    external: true
  redis_password:
    external: true
  ftp_password:
    external: true
  nginx_ssl_cert:
    external: true
  nginx_ssl_key:
    external: true
  nginx_ssl_dhparam:
    external: true
  nginx_ssl_fullchain:
    external: true
  ftp_ssl_cert:
    external: true
  ftp_ssl_key:
    external: true
  splunk_forwarder_pass:
    external: true
  splunk_server_ip:
    external: true

volumes:
  mariadb_data:
    external: true
  wordpress_data:
    external: true
  redis_data:
    external: true
  static_page_data:
    external: true
  logs_data:
    external: true

networks:
  inception_network:
    driver: overlay
    external: true
