services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    container_name: nginx
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception_network
    secrets:
      - nginx_ssl_cert
      - nginx_ssl_key
      - nginx_ssl_dhparam
      - nginx_ssl_fullchain
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 443"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    networks:
      - inception_network
    container_name: mariadb
    restart: on-failure
    secrets:
      - mysql_password
      - mysql_root_password
    env_file:
      - ./env/.env_mariadb

  adminer:
    build: ./requirements/bonus/adminer
    ports:
      - "8080:8080"
    container_name: adminer
    restart: on-failure
    networks:
      - inception_network
    env_file:
      - ./env/.env_adminer
    healthcheck:
      test: ["CMD-SHELL", "php", "-l", "/var/www/html/index.php"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception_network
    secrets:
      - wordpress_db_password
      - wordpress_admin_password
      - wordpress_user_password
      - redis_password
      - ftp_password
    env_file:
      - ./env/.env_wordpress
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: on-failure
    volumes:
      - redis_data:/data:rw
    networks:
      - inception_network
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 10s
      start_period: 40s
      retries: 3

  ftp-server:
    build: ./requirements/bonus/ftp_server
    container_name: ftp-server
    ports:
      - "2121:2121"
      - "21100-21110:21100-21110"
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception_network
    secrets:
      - ftp_password
      - ftp_ssl_cert
      - ftp_ssl_key
    env_file:
      - ./env/.env_ftp_server

  splunk-forwarder:
    build: ./requirements/bonus/splunk_forwarder
    container_name: splunk-forwarder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - logs_data:/mnt/log_backups
    env_file:
      - ./env/.env_splunk_forwarder
    secrets:
      - splunk_forwarder_pass
      - splunk_server_ip
    tty: true
    restart: on-failure

  static-page:
    build: ./requirements/bonus/static_page
    container_name: static-page
    restart: on-failure
    volumes:
      - static_page_data:/var/www/html
    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000\")' || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 15s
      retries: 3

secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  wordpress_db_password:
    file: ./secrets/wordpress_db_password.txt
  wordpress_admin_password:
    file: ./secrets/wordpress_admin_password.txt
  wordpress_user_password:
    file: ./secrets/wordpress_user_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
  ftp_password:
    file: ./secrets/ftp_password.txt
  nginx_ssl_cert:
    file: ./secrets/nginx_ssl_cert.pem
  nginx_ssl_key:
    file: ./secrets/nginx_ssl_key.pem
  nginx_ssl_dhparam:
    file: ./secrets/nginx_ssl_dhparam.pem
  nginx_ssl_fullchain:
    file: ./secrets/nginx_ssl_fullchain.pem
  ftp_ssl_cert:
    file: ./secrets/ftp_ssl_cert.pem
  ftp_ssl_key:
    file: ./secrets/ftp_ssl_key.pem
  splunk_forwarder_pass:
    file: ./secrets/splunk_forwarder_pass.txt
  splunk_server_ip:
    file: ./secrets/splunk_server_ip.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mysql
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/redis
  static_page_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/static_page
  logs_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/logs

networks:
  inception_network:
